import { readFile } from "node:fs/promises";
import path from "node:path";

/**
 * Translation overrides — checked-in human edits that take precedence
 * over both cache and translator output.
 *
 * Convention: an override at
 *
 *     <rootDir>/<overridesDir>/<locale>/<relativeSourcePath>
 *
 * is the canonical translation for that (locale, source) pair. The
 * build hook stages it directly, skipping the cache lookup, the
 * translator call, and the R2 write-back. Overrides are deliberately
 * *not* cached in R2: they are source-controlled artefacts the
 * operator wants to manage by hand, not machine-generated bytes.
 *
 * The path mirrors the source layout (and extension), so a `.mdx`
 * source has a `.mdx` override; the loader does no extension
 * coercion.
 */

export interface ReadOverrideOptions {
  /** Astro project root (absolute filesystem path). */
  rootDir: string;
  /** `overridesDir` from resolved options, e.g. `"./i18n/overrides"`. */
  overridesDir: string;
  /** Target locale, e.g. `"pt-BR"`. */
  locale: string;
  /** Source file path relative to `sourceDir`, e.g. `"publications/sample.md"`. */
  relativeSourcePath: string;
}

/**
 * Resolve and read the override file for a (locale, source) pair.
 *
 * Returns the file contents on hit, or `null` when no override exists.
 * Any error other than `ENOENT` propagates so a permission problem or
 * a malformed `overridesDir` config surfaces loudly rather than
 * silently degrading to "no override".
 */
export async function readOverride(
  opts: ReadOverrideOptions,
): Promise<string | null> {
  const overridePath = resolveOverridePath(opts);
  try {
    return await readFile(overridePath, "utf8");
  } catch (err) {
    if (isNodeNotFoundError(err)) return null;
    throw err;
  }
}

/**
 * Compute the absolute filesystem path the override at the given
 * (locale, source) pair would live at. Exposed (rather than inlined
 * in `readOverride`) so callers that want to log the candidate path
 * don't have to duplicate the join logic.
 */
export function resolveOverridePath(opts: ReadOverrideOptions): string {
  return path.resolve(
    opts.rootDir,
    opts.overridesDir,
    opts.locale,
    opts.relativeSourcePath,
  );
}

function isNodeNotFoundError(err: unknown): boolean {
  return (
    err instanceof Error && (err as NodeJS.ErrnoException).code === "ENOENT"
  );
}
