// This file is generated by npm run icons

export type IconName =
  | "arrowRight"
  | "arrowUpRight"
  | "blog"
  | "bluesky"
  | "bolt"
  | "chevronUpDown"
  | "hand"
  | "hidden"
  | "presentation"
  | "publication"
  | "search"
  | "shield"
  | "transparent"
  | "video"
  | "x";
