/**
 * Route-shim generation. For each `routes` entry, emits an `.astro`
 * shim into the build cache that imports the source page, provides
 * its own `getStaticPaths` enumerating non-default locales, and
 * renders the source as a child. Regenerated every build so config
 * changes take effect immediately.
 */

export interface DerivedUrlPattern {
  /**
   * URL pattern with `src/pages/` and `.astro` stripped and any
   * trailing `/index` removed. The integration prefixes with
   * `[lang]/` for the `injectRoute` call.
   */
  pattern: string;
  /** `true` when the source contains at least one `[param]` segment. */
  isDynamic: boolean;
}

/**
 * `src/pages/[slug].astro`         → `{ "[slug]",         dynamic }`
 * `src/pages/people/[slug].astro`  → `{ "people/[slug]",  dynamic }`
 * `src/pages/about.astro`          → `{ "about",          static  }`
 * `src/pages/index.astro`          → `{ "",               static  }`
 * `src/pages/blog/[...slug].astro` → `{ "blog/[...slug]", dynamic }`
 */
export function deriveUrlPattern(sourcePath: string): DerivedUrlPattern {
  const normalised = stripLeadingSlashes(sourcePath.replaceAll("\\", "/"));
  const stripped = normalised.replace(/^src\/pages\//, "").replace(/\.astro$/, "");
  // Drop a trailing `/index` — section indexes route to the bare URL.
  const pattern = stripped.replace(/(^|\/)index$/, "");
  // `pattern` is dynamic iff it contains a `[param]` segment. We
  // detect that via two `indexOf`s rather than a regex like
  // `/\[[^\]]+\]/` because the regex is unanchored and backtracks
  // quadratically on pathological inputs (CodeQL js/polynomial-redos).
  // File paths never hit that path in practice, but the linear scan
  // is just as readable and costs nothing.
  const openBracket = pattern.indexOf("[");
  const isDynamic = openBracket !== -1 && pattern.indexOf("]", openBracket + 1) !== -1;
  return { pattern, isDynamic };
}

/**
 * Strip leading `/` characters in linear time. Equivalent to
 * `.replace(/^\/+/, "")` but free of regex backtracking concerns.
 */
function stripLeadingSlashes(s: string): string {
  let start = 0;
  while (start < s.length && s.charCodeAt(start) === 47 /* "/" */) start++;
  return start === 0 ? s : s.slice(start);
}

export interface GenerateShimSourceInput {
  /** Bundler-resolvable path from `shimDir`; backslashes normalised. */
  relativeImportPath: string;
  /** Whether the source declares its own `getStaticPaths`. */
  isDynamic: boolean;
  /**
   * Non-default locales only. The default locale is excluded —
   * `prefixDefaultLocale: false` already serves it at the unprefixed
   * path, so a `/<defaultLocale>/<slug>` shim would duplicate routes.
   */
  locales: ReadonlyArray<string>;
  /**
   * Extra modules to import at the top of the shim's frontmatter,
   * BEFORE the source page import. Bare `import "<path>"` statements
   * are emitted in order. Each path must already be resolvable from
   * the shim's location (the integration computes relative paths via
   * `path.relative(shimDir, absoluteTarget)`).
   *
   * Used to inject CSS dependencies (typically a project-wide
   * stylesheet) so Astro's per-route `<link rel="stylesheet">`
   * logic sees them as direct dependencies of the shim's route — it
   * does NOT follow CSS through `<SourcePage />` rendered as a child
   * component, which is why a shim that only imports the source page
   * gets no stylesheet links emitted.
   */
  imports?: ReadonlyArray<string>;
}

/**
 * Pure renderer for the shim source. Dynamic and static branches are
 * separate templates because Astro's compiler is sensitive to the
 * top-level shape of `getStaticPaths` and a conditional template
 * obscured the output without saving code.
 */
export function generateShimSource(input: GenerateShimSourceInput): string {
  const localesLiteral = JSON.stringify(input.locales);
  const importPath = input.relativeImportPath.replaceAll("\\", "/");

  // Side-effect imports (`import "..."`) emitted BEFORE the source
  // page import. Order matters for CSS only insofar as Vite cares
  // about determinism; it doesn't affect cascade because each file
  // is its own scoped chunk. Backslash normalisation matches the
  // source-page import for cross-platform safety.
  const extraImports = (input.imports ?? []).map((p) => `import "${p.replaceAll("\\", "/")}";`);

  // Locales literal is inlined inside `getStaticPaths` — Astro lifts
  // it into its own module for static-path generation and module-
  // level declarations don't survive the lift.
  if (input.isDynamic) {
    return [
      "---",
      "// Auto-generated by polystella. Do not edit; regenerated on every build.",
      ...extraImports,
      `import SourcePage, { getStaticPaths as sourceGetStaticPaths } from "${importPath}";`,
      "",
      "export async function getStaticPaths() {",
      "  const sourcePaths = await sourceGetStaticPaths();",
      `  const locales = ${localesLiteral};`,
      "  return sourcePaths.flatMap((sp) =>",
      "    locales.map((lang) => ({",
      "      params: { ...sp.params, lang },",
      "      props: sp.props,",
      "    })),",
      "  );",
      "}",
      "---",
      "",
      "<SourcePage />",
      "",
    ].join("\n");
  }

  return [
    "---",
    "// Auto-generated by polystella. Do not edit; regenerated on every build.",
    ...extraImports,
    `import SourcePage from "${importPath}";`,
    "",
    "export function getStaticPaths() {",
    `  const locales = ${localesLiteral};`,
    "  return locales.map((lang) => ({ params: { lang } }));",
    "}",
    "---",
    "",
    "<SourcePage />",
    "",
  ].join("\n");
}
