/**
 * Route-shim generation. For each `routes` entry, emits an `.astro`
 * shim into the build cache that imports the source page, provides
 * its own `getStaticPaths` enumerating non-default locales, and
 * renders the source as a child. Regenerated every build so config
 * changes take effect immediately.
 */

export interface DerivedUrlPattern {
  /**
   * URL pattern with `src/pages/` and `.astro` stripped and any
   * trailing `/index` removed. The integration prefixes with
   * `[lang]/` for the `injectRoute` call.
   */
  pattern: string;
  /** `true` when the source contains at least one `[param]` segment. */
  isDynamic: boolean;
}

/**
 * `src/pages/[slug].astro`         → `{ "[slug]",         dynamic }`
 * `src/pages/people/[slug].astro`  → `{ "people/[slug]",  dynamic }`
 * `src/pages/about.astro`          → `{ "about",          static  }`
 * `src/pages/index.astro`          → `{ "",               static  }`
 * `src/pages/blog/[...slug].astro` → `{ "blog/[...slug]", dynamic }`
 */
export function deriveUrlPattern(sourcePath: string): DerivedUrlPattern {
  const normalised = sourcePath.replace(/\\/g, "/").replace(/^\/+/, "");
  const stripped = normalised.replace(/^src\/pages\//, "").replace(/\.astro$/, "");
  // Drop a trailing `/index` — section indexes route to the bare URL.
  const pattern = stripped.replace(/(^|\/)index$/, "");
  const isDynamic = /\[[^\]]+\]/.test(pattern);
  return { pattern, isDynamic };
}

export interface GenerateShimSourceInput {
  /** Bundler-resolvable path from `shimDir`; backslashes normalised. */
  relativeImportPath: string;
  /** Whether the source declares its own `getStaticPaths`. */
  isDynamic: boolean;
  /**
   * Non-default locales only. The default locale is excluded —
   * `prefixDefaultLocale: false` already serves it at the unprefixed
   * path, so a `/<defaultLocale>/<slug>` shim would duplicate routes.
   */
  locales: ReadonlyArray<string>;
}

/**
 * Pure renderer for the shim source. Dynamic and static branches are
 * separate templates because Astro's compiler is sensitive to the
 * top-level shape of `getStaticPaths` and a conditional template
 * obscured the output without saving code.
 */
export function generateShimSource(input: GenerateShimSourceInput): string {
  const localesLiteral = JSON.stringify(input.locales);
  const importPath = input.relativeImportPath.replace(/\\/g, "/");

  // Locales literal is inlined inside `getStaticPaths` — Astro lifts
  // it into its own module for static-path generation and module-
  // level declarations don't survive the lift.
  if (input.isDynamic) {
    return [
      "---",
      "// Auto-generated by polystella. Do not edit; regenerated on every build.",
      `import SourcePage, { getStaticPaths as sourceGetStaticPaths } from "${importPath}";`,
      "",
      "export async function getStaticPaths() {",
      "  const sourcePaths = await sourceGetStaticPaths();",
      `  const locales = ${localesLiteral};`,
      "  return sourcePaths.flatMap((sp) =>",
      "    locales.map((lang) => ({",
      "      params: { ...sp.params, lang },",
      "      props: sp.props,",
      "    })),",
      "  );",
      "}",
      "---",
      "",
      "<SourcePage />",
      "",
    ].join("\n");
  }

  return [
    "---",
    "// Auto-generated by polystella. Do not edit; regenerated on every build.",
    `import SourcePage from "${importPath}";`,
    "",
    "export function getStaticPaths() {",
    `  const locales = ${localesLiteral};`,
    "  return locales.map((lang) => ({ params: { lang } }));",
    "}",
    "---",
    "",
    "<SourcePage />",
    "",
  ].join("\n");
}
